apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: alerter
build:
  local:
    push: false
  artifacts:
    - image: dev.local/alerter-api
      docker:
        dockerfile: build/Dockerfile
        buildArgs:
          SERVICE: api
    - image: dev.local/alerter-checker
      docker:
        dockerfile: build/Dockerfile
        buildArgs:
          SERVICE: checker
    - image: dev.local/alerter-evaluator
      docker:
        dockerfile: build/Dockerfile
        buildArgs:
          SERVICE: evaluator
manifests:
  rawYaml:
    - deploy/k8s/knative/api-service.yaml
    - deploy/k8s/eventing/broker.yaml
    - deploy/k8s/eventing/checker-service.yaml
    - deploy/k8s/eventing/evaluator-service.yaml
    - deploy/k8s/eventing/triggers.yaml
    - deploy/k8s/eventing/pingsource.yaml
deploy:
  kubectl: {}
  statusCheck: false
