apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: alerter-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "5"
    spec:
      containers:
        - image: {{ .Values.image.registry }}/alerter-api:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: ALERTER_LOG_FORMAT
              value: text
            - name: ALERTER_DB_DSN
              value: postgres://alerter:{{ .Values.postgres.password }}@postgres:5432/alerter?sslmode=disable
            - name: ALERTER_SINK_URL
              value: http://kafka-broker-ingress.knative-eventing.svc.cluster.local/{{ .Release.Namespace }}/alerter
          readinessProbe:
            httpGet:
              path: /readyz
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
