apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: demo-monitor
spec:
  schedule: {{ .Values.pingSchedule | quote }}
  contentType: application/json
  data: {{ .Values.demoMonitor | quote }}
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: alerter
