apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: checker-on-tick
spec:
  broker: alerter
  filter:
    attributes:
      type: io.alerter.check.requested
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: checker
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: evaluator-on-check-completed
spec:
  broker: alerter
  filter:
    attributes:
      type: io.alerter.check.completed
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: evaluator
